### ISSUE TITLE
預先判斷郵箱或手機佔用

### ISSUE THREAD

**Issue by edlee-me** [vision1626/frontend_dev#10]
输入未注册手机号与其他信息后，点击发送验证码可成功发送验证码。应先判断该号码是否注册，若未注册则应提示“无此注册手机用户”。

**Comment by latma** [comment]
url:services/service.php?m=user&a=check_account_exist
data:{mobile or email}只能一个
return:{status,msg}status=1表示电话或者邮箱已存在

**Comment by latma** [comment]
更新返回状态代码：
url:services/service.php?m=user&a=check_account_exist
data:{mobile or email}只能一个
return:{status,msg}
status{
0:无效参数(手机、邮箱都不填),
-1:非法操作(手机、邮箱都填了),
-2:无效的手机号码,
-3:无效的电子邮箱,
-4:无此注册用户,
1:账号已存在
}

**Comment by bg7jqc** [comment]
依然存在bug（＃36）so重开此问题

**Comment by bg7jqc** [comment]
FIXED
