### ISSUE TITLE
通过手机成功找回密码后，隐藏跳到其他表单的链接

### ISSUE THREAD

**Issue by edlee-me** [vision1626/frontend_dev#11]
通过手机成功找回密码后，页面应提示“成功找回密码”且删掉“审核请求”及不应出现“手机找回密码页”其他表单元素

**Comment by sogaaa** [comment]
![image](https://cloud.githubusercontent.com/assets/5166665/11436286/6e3b34c8-951e-11e5-9085-03e61a377169.png)

**Comment by sogaaa** [comment]
@jonexiu  这个是手机找回密码，跟手机更换密码是不一样的。手机找回密码不需审核立即生效。
