### ISSUE TITLE
TA的潮品页，未登录状态下无法点击”喜欢“按钮

### ISSUE THREAD

**Issue by sogaaa** [vision1626/frontend_dev#133]
![image](https://cloud.githubusercontent.com/assets/5166665/12319953/a93de038-bae0-11e5-9337-9b3302ba01bf.png)

**Comment by bg7jqc** [comment]
后台返回
result.status:0
result.msg: "请登录！"

**Comment by latma** [comment]
目前规则是搭配要登陆才能点击喜欢，如果需要改需求另提
