### ISSUE TITLE
我的潮品WAP版缺陷及优化

### ISSUE THREAD

**Issue by sogaaa** [vision1626/frontend_dev#178]
1、汉堡菜单列表，增加单个菜单热区，铺满至整行。
2、首页点击“用户昵称”进入我的潮品页，未默认展示“新动态”。
3、页脚“帮助中心”栏，“帮助中心”按钮后新增 “用户反馈” 按钮。
4、在我的潮品页，点击汉堡菜单再回到“我的潮品页”时，底部菜单里消失/展示位置未置底。

**Comment by bg7jqc** [comment]
2、首页点击“用户昵称”进入我的潮品页，未默认展示“新动态”。
找老马
