### ISSUE TITLE
“10天内免登陆”与“忘记密码”字体未对齐

### ISSUE THREAD

**Issue by edlee-me** [vision1626/frontend_dev#19]
“10天内免登陆”与“忘记密码”字体未对其

**Comment by edlee-me** [comment]
未發現問題，請產品人員重現

**Comment by sogaaa** [comment]
![image](https://cloud.githubusercontent.com/assets/5166665/11329862/b8f91452-91dc-11e5-9a99-1f48dfb4542c.png)
