### ISSUE TITLE
输入错误手机号与正确验证码，立即注册按钮未变成可点击样式

### ISSUE THREAD

**Issue by sogaaa** [vision1626/frontend_dev#27]
输入错误手机号与正确验证码后，再次输入正确手机号。
1.立即注册按钮未变成可点击样式
2.手机号输入框未做数字限制，应限制为最多可输入11为数

![default](https://cloud.githubusercontent.com/assets/5166665/11266501/f038dc7c-8edf-11e5-800b-f0d21053a08b.png)

**Comment by edlee-me** [comment]
手機號和郵箱的輸入框，不能限制字數

**Comment by angusouyang** [comment]
已解决问题一
