### ISSUE TITLE
输入已注册邮箱地址，切换输入框后未及时提示“此邮箱已被注册”。

### ISSUE THREAD

**Issue by sogaaa** [vision1626/frontend_dev#29]
输入已注册邮箱地址与其他信息后点击“注册”，提示“此邮箱已被注册”。应在用户输完邮箱并切换输入框时提示，减少用户操作成本。

**Comment by edlee-me** [comment]
与#10重复

**Comment by latma** [comment]
url:services/service.php?m=user&a=check_account_exist
data:{mobile or email}只能一个
return:{status,msg}status=1表示电话或者邮箱已存在

**Comment by angusouyang** [comment]
FIXED
