### ISSUE TITLE
服务条款页未做手机版自适应。

### ISSUE THREAD

**Issue by sogaaa** [vision1626/frontend_dev#30]
点击“1626服务条款”按钮弹出的服务条款页未做自适应。

![default](https://cloud.githubusercontent.com/assets/5166665/11266846/95c4f7dc-8ee2-11e5-9a9f-291c19dbef4a.png)

**Comment by edlee-me** [comment]
此頁面屬於幫助中心，需產品人員重新規劃一下？

**Comment by edlee-me** [comment]
同#31，用彈窗處理

**Comment by edlee-me** [comment]
FIXED
