### ISSUE TITLE
“手机找回密码”页标题显示为“手机更改密码”

### ISSUE THREAD

**Issue by sogaaa** [vision1626/frontend_dev#32]
“邮箱找回密码”页点击“手机找回密码”按钮，“手机找回密码”页标题显示为“手机更改密码”，应显示为“手机找回密码”

![default](https://cloud.githubusercontent.com/assets/5166665/11267015/c517ce1e-8ee3-11e5-97d6-3003b4f4f7cc.png)

**Comment by edlee-me** [comment]
已統一為「手機更改密碼」

**Comment by sogaaa** [comment]
应统一改成「手机找回密码」，与邮箱找回密码统一，且用户目的是忘记密码后要找回密码
