### ISSUE TITLE
手机找回密码页，用tab切换表单输入完成后，“获取手机验证码”按钮未变成可点击样式

### ISSUE THREAD

**Issue by sogaaa** [vision1626/frontend_dev#33]
手机找回密码页，用tab切换表单输入完成后，“获取手机验证码”按钮未变成可点击样式

![image](https://cloud.githubusercontent.com/assets/5166665/11267203/d89bd344-8ee4-11e5-9c21-f16f6ec5cb45.png)

**Comment by bg7jqc** [comment]
无法重现错误

**Comment by sogaaa** [comment]
填完所有表单后，删除除验证码外其他表单内容，再填写内容后按钮状态未变更。

**Comment by edlee-me** [comment]
如此蛋疼的用戶？
输入后，离开输入框，按鈕狀態會變化。否則無法實現鍵入時判斷信息是否合法：
1. 手機，在輸入第11個可判斷
2. 如果是郵箱，不能限制字數，無法判斷鍵入是否完成
3. 密碼，不能限制字數，無法判斷鍵入是否完成
只能解決第1項。

**Comment by sogaaa** [comment]
该页是手机找回密码页，不存在第2点。
第3点建议两个密码相同则可点击，若不符合规则会有错误提示

**Comment by bg7jqc** [comment]
其实…………这点算bug？
