### ISSUE TITLE
用户名密码正确但登录失败

### ISSUE THREAD

**Issue by edlee-me** [vision1626/frontend_dev#4]
用户名密码正确但登录失败

**Comment by latma** [comment]
后端用户名登陆限制已取消

**Comment by edlee-me** [comment]
需要取消只允許郵箱或手機登錄的限制

**Comment by edlee-me** [comment]
我已增加用户图标，在ui.less，及更新了font文件sftp://192.168.0.230//home/vhost/www.hi1626.com/tpl/hi1626/fonts

请修改以下代码
login.jade
line 40
i.icon.icon-sml.icon-phone
请改为
**i.icon.icon-sml.icon-user**

**Comment by bg7jqc** [comment]
目前登录用户名输入框允许输入 手机、email、［0-9a-zA-Z］

**Comment by bg7jqc** [comment]
登录和注册页面切换时，未实现刷新验证码功能

**Comment by sogaaa** [comment]
无法登陆，如用户名a_9986402，密码123456
![image](https://cloud.githubusercontent.com/assets/5166665/11356552/bf00d4a8-9299-11e5-9b7f-c0f4dedb8104.png)

**Comment by bg7jqc** [comment]
判断规则已包含 “_",".","-"
