### ISSUE TITLE
手机号更换找回密码页，“旧手机号”输入框未判断手机号是否已注册

### ISSUE THREAD

**Issue by sogaaa** [vision1626/frontend_dev#41]
手机号更换找回密码页，“旧手机号”输入框输入未注册手机，其他信息输入完成后仍可发送短信到新手机。

建议：对旧手机进行判断，如检测为未注册用户则在输入框右侧红色字提示“该手机未注册”

**Comment by bg7jqc** [comment]
sorry 按错

**Comment by bg7jqc** [comment]
FIXED
