### ISSUE TITLE
手机号换成邮箱后“发送验证”上文字未对应更新

### ISSUE THREAD

**Issue by sogaaa** [vision1626/frontend_dev#42]
注册页，注册页，手机号换成邮箱后“发送验证”按钮亮起，但按钮上文字未对应更新

![image](https://cloud.githubusercontent.com/assets/5166665/11356688/01d92568-929b-11e5-9b14-8053b8f64e25.png)

**Comment by bg7jqc** [comment]
击发验证事件从blur改为了keyup
