### ISSUE TITLE
更改手机号找回密码页，未做新旧手机号重复、密码不一致判断

### ISSUE THREAD

**Issue by sogaaa** [vision1626/frontend_dev#44]
更改手机号找回密码页
1、新旧手机号为同一个号码时提示“新号码不能与旧号码一致”
2、密码不一致时提示“两次输入的密码不相同”。

![image](https://cloud.githubusercontent.com/assets/5166665/11357015/5fd84f88-929e-11e5-9e24-7045747cae0c.png)

**Comment by bg7jqc** [comment]
此问题由 ＃47 表单错误提示样式优化 修正
