### ISSUE TITLE
重置密码页，输入密码后点击”提交“提示”请先输入验证码“

### ISSUE THREAD

**Issue by sogaaa** [vision1626/frontend_dev#52]
不存在输入验证码判断

![image](https://cloud.githubusercontent.com/assets/5166665/11392528/586b25d4-9395-11e5-8b01-4e27684d3311.png)

**Comment by edlee-me** [comment]
密码重置一次之后，你再点击邮件的链接，API就会返回这个东西。

**Comment by sogaaa** [comment]
@jonexiu 这种情况可提示链接失效，即点击链接进入该页面时显示页面失效。
