### ISSUE TITLE
注册按钮状态显示bug

### ISSUE THREAD

**Issue by vingochan** [vision1626/frontend_dev#61]
![aa](https://cloud.githubusercontent.com/assets/15973713/11463018/40fa25d8-9757-11e5-9b4f-6e19e8ad1346.png)

如图所示，注册按钮状态显示bug，不排除其他涉及手机验证码的表单按钮存在同样问题。
火狐浏览器

**Comment by vingochan** [comment]
后续测试发现不只是状态显示bug，是不能点击提交了。

**Comment by edlee-me** [comment]
所有需要手机验证码的地方，成功发送验证码后，提交时无需提交PC验证码，请获手机取验证码之后禁止手机和pc验证码的修改

**Comment by vingochan** [comment]
![ooo](https://cloud.githubusercontent.com/assets/15973713/11466940/d42da6cc-977f-11e5-8014-5de2847cdc99.png)
“重新发送”需要重新填写验证码！！！

**Comment by edlee-me** [comment]
@oeeeeeeeeeeeee 請繼續跟進此問題。按「重新發送」可刷新PC驗證碼，並在旁邊提示「請輸入圖片中的數字」

**Comment by vingochan** [comment]
@jonexiu 涉及需要发送手机验证码的页面逻辑，都应该是这样的，不单是注册页。
