### ISSUE TITLE
注册页发送手机验证码后倒计时结束点击“重新发送”按钮，提示“验证码错误”且不可输入验证码

### ISSUE THREAD

**Issue by sogaaa** [vision1626/frontend_dev#63]
注册页发送手机验证码后倒计时结束点击“重新发送”按钮，提示“验证码错误”且不可输入验证码

![image](https://cloud.githubusercontent.com/assets/5166665/11490567/b52a981c-9814-11e5-9318-3b54e63cb146.png)

**Comment by edlee-me** [comment]
與 #61 一致
