### ISSUE TITLE
注册成功后修改昵称，个人中心的昵称未对应更新

### ISSUE THREAD

**Issue by sogaaa** [vision1626/frontend_dev#64]
如图：

![image](https://cloud.githubusercontent.com/assets/5166665/11490595/05b47280-9815-11e5-99d7-f979c493d496.png)

**Comment by edlee-me** [comment]
交由 @latma 處理。

**Comment by latma** [comment]
@jonexiu 更新SVN，修改前端昵称检查。
url:/services/service.php?m=user&a=check_nickname_exist,
dataType:json,
data:{nick_name:aaaa},
return:{status,msg}
{status
0:非法操作
-1:昵称含非法字符，仅支持中英文、数字
-2:昵称长度为2-20个字符，可由中英文、数字组成
-3:昵称已存在
1:昵称可以使用
}
nick_name请先用encodeURIComponent()编码
