### ISSUE TITLE
鼠标触发右上角“闪电”标志展开后，鼠标移出热区不建议再缩回去。

### ISSUE THREAD

**Issue by sogaaa** [vision1626/frontend_dev#73]
![image](https://cloud.githubusercontent.com/assets/5166665/12013328/551d40a0-ad4f-11e5-9452-705730643b19.png)

**Comment by edlee-me** [comment]
點解啊？

**Comment by sogaaa** [comment]
@jonexiu 因为在闪电展开的情况下，鼠标左移点击“消息”时会误点到“退出”，又要移动鼠标才能点击目标事件。

**Comment by edlee-me** [comment]
明白，那我改為鼠標離開黑色導航的時候收回吧

**Comment by sogaaa** [comment]
OK
